trigger:
  - master

pool:
  vmImage: ubuntu-latest


steps:
  - script: echo 'Hello World!'
    displayName: 'Saying Hello'
  - task: AzureCLI@2
    displayName: 'Creating resource group'
    inputs: 
      azureSubscription: mytestsubscription
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az group create --name resourcegroupfromdevops-rg --location westeurope